/// A recipe from the official INS recipe book.
///
/// The corpus is a bundled asset and is never generated by the model: the
/// nutritional facts here are the grounding that keeps Gemma from inventing
/// clinical content (ADR-0005).
library;

import 'child_profile.dart';

class Recipe {
  const Recipe({
    required this.id,
    required this.name,
    required this.ingredients,
    required this.preparation,
    required this.ironMg,
    required this.minAgeMonths,
    required this.referenceCostPen,
    this.region,
  });

  final int id;
  final String name;

  /// Ingredient names as they appear in the INS book, lowercase.
  final List<String> ingredients;

  /// Preparation steps, in Spanish — this string is read aloud by TTS.
  final String preparation;

  /// Iron contributed by one serving, in milligrams.
  final double ironMg;

  /// Youngest age this recipe is suitable for, in months.
  final int minAgeMonths;

  /// Indicative cost of one serving, in Peruvian soles.
  final double referenceCostPen;

  /// Null when the recipe is available nationwide.
  final Region? region;

  bool isSuitableFor(int ageMonths) => ageMonths >= minAgeMonths;
}
